dbt_master_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: user
      pass: password
      port: 5432
      dbname: mydatabase
      schema: public # You can set this to the schema you want to use
      threads: 4
